'use client'

import { Toaster } from '@modules/shared/components/ui/toaster'
import { Inter } from 'next/font/google'
import { useEffect } from 'react'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
// 	title: 'Airdrop Farmer',
// 	description: 'Generated by create next app',
// }

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const onUnload = (e: BeforeUnloadEvent) => {
		e.preventDefault()
		return (e.returnValue = '')
	}

	useEffect(() => {
		window.addEventListener('beforeunload', onUnload)

		return () => {
			window.removeEventListener('beforeunload', onUnload)
		}
	}, [])

	return (
		// Permanent dark mode enabled https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually
		<html lang="en" className="dark">
			<body className={inter.className} suppressHydrationWarning={true}>
				<>
					{children}
					<Toaster />
				</>
			</body>
		</html>
	)
}
